### ISSUE TITLE
No md5key on new subscriptions

### ISSUE THREAD

**Issue by kallehauge** [krokedil/dibs-for-woocommerce#24]
Hi! I get a `No md5key` notification when trying to make a new subscription. It works fine with a "Simple Product" purchase so I'm assuming that I have setup everything correct (I have double-checked that I have filled out `MD5 k1` and `MD5 k2`.
I'm assuming that it have something to do with the following logic in `WC_Gateway_Dibs_CC::generate_dibs_form`:

```
if ( WC_Subscriptions_Order::get_total_initial_payment( $order ) == 0 ) {
    $price = 0;
} else {
    $price = WC_Subscriptions_Order::get_total_initial_payment( $order );
    // Subscription payment
    $args['maketicket'] = '1';
}
```

![screen shot 2018-01-29 at 13 31 10](https://user-images.githubusercontent.com/3846700/35510547-c2474dee-04f8-11e8-92ce-c5ca2e61e407.png)

**Comment by kallehauge** [comment]
@NiklasHogefjord do you have any previous knowledge of this? :)

**Comment by NiklasHogefjord** [comment]
Hi @kallehauge, sorry for the late reply.

If you're using the plugin together with WooCommerce Subscriptions you need to turn off md5 key verification in your DIBS backoffice (more info about that here http://docs.krokedil.com/documentation/dibs-for-woocommerce/#5).

DIBS doesn't allow md5 calculation when it's a matter of creating a subscription order (see more under the parameter _maketicket_ here -
 https://tech.dibspayment.com/D2/Hosted/Input_parameters/Standard).

**Comment by kallehauge** [comment]
Arrrh, damn. I hate being the guy who overlooks documentation 🙈  Thank you very much @NiklasHogefjord ! Please accept my PR (#23) as a "thank you for your time" 😄
